### ISSUE TITLE
Take care of run 1 Pt cut in XiC MC (GPT issue)

### ISSUE THREAD

**Issue by cpawley** [jackfrost373/LHCb_Xic_production#39]
This is a generator cut so we should cut both samples slightly above 3.2 GeV

**Comment by jackfrost373** [comment]
This is because otherwise Xic and Lc MC are not comparable in stripping21, as they had different gen.level PT cuts. If we make a tighter cut, we should also apply it to data for MC-Data agreement. (Also ensure that the lower PT bin starts here)

However, perhaps it's best to wait a bit for the upcoming MC request ( see https://github.com/jackfrost373/LcAnalysis_Simon/issues/41 ), because in order to have both
- enough MC to be at least as much as our signal, after all selections
- not have too many MC events produced in our request 
we might have to tighten the gen. level cuts..

**Comment by jackfrost373** [comment]
In the new MC requests this cut is the same between Xic and Lc.
